"""Regenerate logo.svg.

The logo is a spiral, so its path is a few hundred plotted points that nobody
can sensibly edit by hand. Tweak the constants below and re-run instead:

    python assets/logo.py

SEGMENTS controls how many "weeks" the groove is broken into. The dasharray is
derived from the measured path length rather than guessed, so the segments stay
evenly spaced all the way round as the curvature changes.
"""
import math
from pathlib import Path

CX = CY = 32.0
R0, R1 = 7.0, 27.0     # inner and outer radius
TURNS = 3.0
STEPS = 300            # plotted points; high enough to avoid faceting when scaled up
SEGMENTS = 18          # visible marks around the groove
DASH_RATIO = 0.62      # dash : (dash + gap)
COLOR = "#14b8a6"      # mid-tone: legible on both light and dark backgrounds

points = []
for i in range(STEPS + 1):
    t = i / STEPS
    theta = t * TURNS * 2 * math.pi
    r = R0 + (R1 - R0) * t
    points.append((CX + r * math.cos(theta), CY + r * math.sin(theta)))

length = sum(math.dist(points[i], points[i + 1]) for i in range(len(points) - 1))
period = length / SEGMENTS
dash = period * DASH_RATIO
gap = period - dash

d = "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in points)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="spotify-weekly-archive">
  <title>spotify-weekly-archive</title>
  <!-- A record groove broken into segments: one mark per week, spiralling
       outward as the archive grows. Generated by assets/logo.py - do not edit
       the path by hand. -->
  <g fill="none" stroke="{COLOR}" stroke-width="3.2" stroke-linecap="round">
    <path d="{d}" stroke-dasharray="{dash:.2f} {gap:.2f}"/>
  </g>
  <circle cx="{CX:.0f}" cy="{CY:.0f}" r="2.6" fill="{COLOR}"/>
</svg>
'''

out = Path(__file__).with_name("logo.svg")
out.write_text(svg)
print(f"{out.name}: length {length:.1f}, {SEGMENTS} segments, dash {dash:.2f} gap {gap:.2f}")
